name: notion
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [notion-hook]

jobs:
  notion:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3
    - name: Check env existence
      id:   check_env
      uses: andstor/file-existence-action@v1
      with:
        files: ".env"
    - name: Set Env
      if: steps.check_files.outputs.files_exists == 'true'
      run: |
        npm i
        type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
        gh secret list >> .secrets
        node scripts/setSecrets.mjs .secrets
    - name: Create Env
      run: |
        touch .env
        echo NOTION_API_KEY=${{ secrets.NOTION_API_KEY }} >> .env
        echo NOTION_DATABASE_ID=${{ secrets.NOTION_DATABASE_ID }} >> .env
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
    - name: Run Scripts
      run: |
        npm i
        rm -rf ./blog
        node scripts/index.mjs  
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: blog-artifact
        path: blog

  commit-to-repo:
    needs: notion
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
      - name: Remove old blog data
        run: rm -rf ./blog
      - uses: actions/download-artifact@master
        with:
          name: blog-artifact
          path: blog
      - name: Commit blog content changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update blog"
          branch: main
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          disable_globbing: true

