name: notion
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [notion-hook]

jobs:
  notion:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3

    - name: Create env
      run: |
        touch .env
        echo NOTION_TOKEN=${{ secrets.NOTION_TOKEN }} >> .env
        echo NOTION_DATABASE_ID=${{ secrets.NOTION_DATABASE_ID }} >> .env
        echo CLOUDINARY_URL=${{ secrets.CLOUDINARY_URL }} >> .env
        echo CLOUDINARY_UPLOAD_FOLDER=${{ secrets.CLOUDINARY_UPLOAD_FOLDER }} >> .env
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

    - name: Run scripts
      run: |
        npx upload-notion-images-to-cloudinary
        npm i
        rm -rf ./${{ secrets.FOLDER_NAME }}
        node scripts/index.mjs  
        node scripts/frontmatter.mjs 

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: ${{ secrets.FOLDER_NAME }}-artifact
        path: ${{ secrets.FOLDER_NAME }}

    - name: Commit blog content changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "chore: update ${{ secrets.FOLDER_NAME }}"
        branch: main
        file_pattern: "*.mdx"
        commit_user_name: github-actions[bot]
        commit_user_email: github-actions[bot]@users.noreply.github.com
        commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
        disable_globbing: true

