name: notion
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [notion-hook]

jobs:
  notion:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Scripts - current repository
      uses: actions/checkout@v3

    - name: Create Env
      run: |
        touch .env
        echo NOTION_API_KEY=${{ secrets.NOTION_API_KEY }} >> .env
        echo DATABASE_ID=${{ secrets.DATABASE_ID }} >> .env
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        DATABASE_ID: ${{ secrets.DATABASE_ID }}

    - name: Run Scripts
      run: |
        npm i
        rm -rf ./blog
        node index.mjs  

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: blog-artifact
        path: blog

  commit-to-repo:
    needs: notion
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        
      - name: Remove old blog data
        run: rm -rf ./blog

      - uses: actions/download-artifact@master
        with:
          name: blog-artifact
          path: blog

      - name: Commit blog content changes
        run: |
          git add .
          git config --global user.name 'handshou'
          git config --global user.email 'hanselhub@gmail.com'
          git commit -am "chore: update blog"
          git push
