name: Publish to cloudflare
on:
  workflow_run:
    workflows: ["Notion fetch"]
    types:
      - completed

jobs:
  pull-astro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout your repository using git
        uses: actions/checkout@v3
        with:
          repository: handshou/astro-blog
          token: ${{ secrets.PULL_ASTRO_REPO }}
          path: .
      - uses: actions/upload-artifact@master
        with:
          name: blog-artifact
          path: .

  download-posts:
    needs: pull-astro
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: blog-artifact
          path: .
      - run: |
          rm -rf ./src/pages/blog
          mv ./blog ./src/pages
          find ./src/pages/blog/ -type f -name "*.md*" -exec sed -i.bak -nf formatfrontmatter.sed {} \;
          cat ./src/pages/blog/*.md
          npm install --save-dev fs path js-yaml
          node rename.mjs
      - uses: withastro/action@v0
        name: Install, build, and upload your site output
      - uses: actions/upload-artifact@master
        with:
          name: dist-artifact
          path: dist

  publish:
    needs: download-posts
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - uses: actions/download-artifact@master
        with:
          name: dist-artifact
          path: dist

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 53c464573b64e485440feb5a5a36bb22
          projectName: astro-blog
          directory: dist
          # Optional: Enable this if you want to have GitHub Deployments triggered
          # gitHubToken: ${{ secrets.GITHUB_TOKEN }}